"""
### Ui_AudioProcess
音频处理系统Ui交互界面
"""
from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_AudioProcess(object):
    def setupUi(self, AudioProcess):
        AudioProcess.setObjectName("AudioProcess")
        AudioProcess.resize(1078, 684)
        self.gridLayout = QtWidgets.QGridLayout(AudioProcess)
        self.gridLayout.setObjectName("gridLayout")
        self.frame = QtWidgets.QFrame(AudioProcess)
        self.frame.setMinimumSize(QtCore.QSize(0, 0))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.frame)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.line_23 = QtWidgets.QFrame(self.frame)
        self.line_23.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_23.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_23.setObjectName("line_23")
        self.gridLayout_2.addWidget(self.line_23, 3, 4, 1, 2)
        self.line_22 = QtWidgets.QFrame(self.frame)
        self.line_22.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_22.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_22.setObjectName("line_22")
        self.gridLayout_2.addWidget(self.line_22, 1, 4, 1, 2)
        self.titleLayout = QtWidgets.QHBoxLayout()
        self.titleLayout.setObjectName("titleLayout")
        self.titlelabel = QtWidgets.QLabel(self.frame)
        self.titlelabel.setObjectName("titlelabel")
        self.titleLayout.addWidget(self.titlelabel)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.titleLayout.addItem(spacerItem)
        self.helpButton = QtWidgets.QPushButton(self.frame)
        self.helpButton.setObjectName("helpButton")
        self.titleLayout.addWidget(self.helpButton)
        self.gridLayout_2.addLayout(self.titleLayout, 0, 0, 1, 1)
        self.normalizerLayout = QtWidgets.QVBoxLayout()
        self.normalizerLayout.setObjectName("normalizerLayout")
        self.normalizerlabel = QtWidgets.QLabel(self.frame)
        self.normalizerlabel.setObjectName("normalizerlabel")
        self.normalizerLayout.addWidget(self.normalizerlabel)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.normalizerLayout.addItem(spacerItem1)
        self.normalizerConfigLayout_2 = QtWidgets.QHBoxLayout()
        self.normalizerConfigLayout_2.setObjectName("normalizerConfigLayout_2")
        self.configNomalizerTypeLayout = QtWidgets.QVBoxLayout()
        self.configNomalizerTypeLayout.setObjectName("configNomalizerTypeLayout")
        self.maxSilenceNomalizerlabel = QtWidgets.QLabel(self.frame)
        self.maxSilenceNomalizerlabel.setObjectName("maxSilenceNomalizerlabel")
        self.configNomalizerTypeLayout.addWidget(self.maxSilenceNomalizerlabel)
        self.targerNomalizerlabel = QtWidgets.QLabel(self.frame)
        self.targerNomalizerlabel.setObjectName("targerNomalizerlabel")
        self.configNomalizerTypeLayout.addWidget(self.targerNomalizerlabel)
        self.normalizerConfigLayout_2.addLayout(self.configNomalizerTypeLayout)
        self.configNormalizerLayout = QtWidgets.QVBoxLayout()
        self.configNormalizerLayout.setObjectName("configNormalizerLayout")
        self.maxNormalizerlineEdit = QtWidgets.QLineEdit(self.frame)
        self.maxNormalizerlineEdit.setText("")
        self.maxNormalizerlineEdit.setObjectName("maxNormalizerlineEdit")
        self.configNormalizerLayout.addWidget(self.maxNormalizerlineEdit)
        self.targetNormalizerlineEdit = QtWidgets.QLineEdit(self.frame)
        self.targetNormalizerlineEdit.setText("")
        self.targetNormalizerlineEdit.setObjectName("targetNormalizerlineEdit")
        self.configNormalizerLayout.addWidget(self.targetNormalizerlineEdit)
        self.normalizerConfigLayout_2.addLayout(self.configNormalizerLayout)
        self.normalizerLayout.addLayout(self.normalizerConfigLayout_2)
        self.nomalizercomboBox = QtWidgets.QComboBox(self.frame)
        self.nomalizercomboBox.setObjectName("nomalizercomboBox")
        self.nomalizercomboBox.addItem("")
        self.nomalizercomboBox.addItem("")
        self.nomalizercomboBox.addItem("")
        self.normalizerLayout.addWidget(self.nomalizercomboBox)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.normalizerLayout.addItem(spacerItem2)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem3)
        self.muteButton = QtWidgets.QPushButton(self.frame)
        self.muteButton.setObjectName("muteButton")
        self.horizontalLayout_4.addWidget(self.muteButton)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem4)
        self.volumeButton = QtWidgets.QPushButton(self.frame)
        self.volumeButton.setObjectName("volumeButton")
        self.horizontalLayout_4.addWidget(self.volumeButton)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem5)
        self.normalizerLayout.addLayout(self.horizontalLayout_4)
        self.gridLayout_2.addLayout(self.normalizerLayout, 3, 3, 1, 1)
        self.line_24 = QtWidgets.QFrame(self.frame)
        self.line_24.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_24.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_24.setObjectName("line_24")
        self.gridLayout_2.addWidget(self.line_24, 5, 4, 1, 1)
        self.line_15 = QtWidgets.QFrame(self.frame)
        self.line_15.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_15.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_15.setObjectName("line_15")
        self.gridLayout_2.addWidget(self.line_15, 3, 1, 1, 2)
        self.line_13 = QtWidgets.QFrame(self.frame)
        self.line_13.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_13.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_13.setObjectName("line_13")
        self.gridLayout_2.addWidget(self.line_13, 5, 1, 1, 1)
        self.line_18 = QtWidgets.QFrame(self.frame)
        self.line_18.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_18.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_18.setObjectName("line_18")
        self.gridLayout_2.addWidget(self.line_18, 1, 1, 1, 2)
        self.recordLayout = QtWidgets.QVBoxLayout()
        self.recordLayout.setObjectName("recordLayout")
        self.recoedlabel = QtWidgets.QLabel(self.frame)
        self.recoedlabel.setObjectName("recoedlabel")
        self.recordLayout.addWidget(self.recoedlabel)
        self.configRecordLayout_2 = QtWidgets.QHBoxLayout()
        self.configRecordLayout_2.setObjectName("configRecordLayout_2")
        self.configRecordtypeLayout = QtWidgets.QVBoxLayout()
        self.configRecordtypeLayout.setObjectName("configRecordtypeLayout")
        self.micidRecordlabel = QtWidgets.QLabel(self.frame)
        self.micidRecordlabel.setObjectName("micidRecordlabel")
        self.configRecordtypeLayout.addWidget(self.micidRecordlabel)
        self.chunkRecordlabel = QtWidgets.QLabel(self.frame)
        self.chunkRecordlabel.setObjectName("chunkRecordlabel")
        self.configRecordtypeLayout.addWidget(self.chunkRecordlabel)
        self.channelsRecordlabel = QtWidgets.QLabel(self.frame)
        self.channelsRecordlabel.setObjectName("channelsRecordlabel")
        self.configRecordtypeLayout.addWidget(self.channelsRecordlabel)
        self.rateRecordlabel = QtWidgets.QLabel(self.frame)
        self.rateRecordlabel.setObjectName("rateRecordlabel")
        self.configRecordtypeLayout.addWidget(self.rateRecordlabel)
        self.timelabel = QtWidgets.QLabel(self.frame)
        self.timelabel.setObjectName("timelabel")
        self.configRecordtypeLayout.addWidget(self.timelabel)
        self.configRecordLayout_2.addLayout(self.configRecordtypeLayout)
        self.configRecordLayout = QtWidgets.QVBoxLayout()
        self.configRecordLayout.setObjectName("configRecordLayout")
        self.micidRecordlineEdit = QtWidgets.QLineEdit(self.frame)
        self.micidRecordlineEdit.setText("")
        self.micidRecordlineEdit.setObjectName("micidRecordlineEdit")
        self.configRecordLayout.addWidget(self.micidRecordlineEdit)
        self.chunkRecordlineEdit = QtWidgets.QLineEdit(self.frame)
        self.chunkRecordlineEdit.setText("")
        self.chunkRecordlineEdit.setObjectName("chunkRecordlineEdit")
        self.configRecordLayout.addWidget(self.chunkRecordlineEdit)
        self.channelsRecordlineEdit = QtWidgets.QLineEdit(self.frame)
        self.channelsRecordlineEdit.setText("")
        self.channelsRecordlineEdit.setObjectName("channelsRecordlineEdit")
        self.configRecordLayout.addWidget(self.channelsRecordlineEdit)
        self.rateRecordlineEdit = QtWidgets.QLineEdit(self.frame)
        self.rateRecordlineEdit.setText("")
        self.rateRecordlineEdit.setObjectName("rateRecordlineEdit")
        self.configRecordLayout.addWidget(self.rateRecordlineEdit)
        self.timeRecordlineEdit = QtWidgets.QLineEdit(self.frame)
        self.timeRecordlineEdit.setText("")
        self.timeRecordlineEdit.setObjectName("timeRecordlineEdit")
        self.configRecordLayout.addWidget(self.timeRecordlineEdit)
        self.configRecordLayout_2.addLayout(self.configRecordLayout)
        self.recordLayout.addLayout(self.configRecordLayout_2)
        self.functionRecordLayout = QtWidgets.QHBoxLayout()
        self.functionRecordLayout.setObjectName("functionRecordLayout")
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.functionRecordLayout.addItem(spacerItem6)
        self.micButton = QtWidgets.QPushButton(self.frame)
        self.micButton.setObjectName("micButton")
        self.functionRecordLayout.addWidget(self.micButton)
        spacerItem7 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.functionRecordLayout.addItem(spacerItem7)
        self.recordButton = QtWidgets.QPushButton(self.frame)
        self.recordButton.setObjectName("recordButton")
        self.functionRecordLayout.addWidget(self.recordButton)
        spacerItem8 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.functionRecordLayout.addItem(spacerItem8)
        self.recordLayout.addLayout(self.functionRecordLayout)
        self.gridLayout_2.addLayout(self.recordLayout, 3, 6, 1, 1)
        self.line_28 = QtWidgets.QFrame(self.frame)
        self.line_28.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_28.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_28.setObjectName("line_28")
        self.gridLayout_2.addWidget(self.line_28, 4, 5, 1, 2)
        self.databaseLayout = QtWidgets.QHBoxLayout()
        self.databaseLayout.setObjectName("databaseLayout")
        self.configtypeDbLayout = QtWidgets.QVBoxLayout()
        self.configtypeDbLayout.setObjectName("configtypeDbLayout")
        self.configDblabel = QtWidgets.QLabel(self.frame)
        self.configDblabel.setObjectName("configDblabel")
        self.configtypeDbLayout.addWidget(self.configDblabel)
        spacerItem9 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.configtypeDbLayout.addItem(spacerItem9)
        self.hostlDbabel = QtWidgets.QLabel(self.frame)
        self.hostlDbabel.setObjectName("hostlDbabel")
        self.configtypeDbLayout.addWidget(self.hostlDbabel)
        spacerItem10 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.configtypeDbLayout.addItem(spacerItem10)
        self.userDblabel = QtWidgets.QLabel(self.frame)
        self.userDblabel.setObjectName("userDblabel")
        self.configtypeDbLayout.addWidget(self.userDblabel)
        spacerItem11 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.configtypeDbLayout.addItem(spacerItem11)
        self.passwdlabel = QtWidgets.QLabel(self.frame)
        self.passwdlabel.setObjectName("passwdlabel")
        self.configtypeDbLayout.addWidget(self.passwdlabel)
        spacerItem12 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.configtypeDbLayout.addItem(spacerItem12)
        self.databaseDblabel = QtWidgets.QLabel(self.frame)
        self.databaseDblabel.setObjectName("databaseDblabel")
        self.configtypeDbLayout.addWidget(self.databaseDblabel)
        spacerItem13 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.configtypeDbLayout.addItem(spacerItem13)
        self.portlDbabel = QtWidgets.QLabel(self.frame)
        self.portlDbabel.setObjectName("portlDbabel")
        self.configtypeDbLayout.addWidget(self.portlDbabel)
        spacerItem14 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.configtypeDbLayout.addItem(spacerItem14)
        self.tablelabel = QtWidgets.QLabel(self.frame)
        self.tablelabel.setObjectName("tablelabel")
        self.configtypeDbLayout.addWidget(self.tablelabel)
        self.databaseLayout.addLayout(self.configtypeDbLayout)
        self.insertDbLayout = QtWidgets.QVBoxLayout()
        self.insertDbLayout.setObjectName("insertDbLayout")
        self.insertDblabel = QtWidgets.QLabel(self.frame)
        self.insertDblabel.setObjectName("insertDblabel")
        self.insertDbLayout.addWidget(self.insertDblabel)
        spacerItem15 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.insertDbLayout.addItem(spacerItem15)
        self.hostDblineEdit = QtWidgets.QLineEdit(self.frame)
        self.hostDblineEdit.setText("")
        self.hostDblineEdit.setObjectName("hostDblineEdit")
        self.insertDbLayout.addWidget(self.hostDblineEdit)
        spacerItem16 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.insertDbLayout.addItem(spacerItem16)
        self.userDblineEdit = QtWidgets.QLineEdit(self.frame)
        self.userDblineEdit.setText("")
        self.userDblineEdit.setObjectName("userDblineEdit")
        self.insertDbLayout.addWidget(self.userDblineEdit)
        spacerItem17 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.insertDbLayout.addItem(spacerItem17)
        self.pswdDblineEdit = QtWidgets.QLineEdit(self.frame)
        self.pswdDblineEdit.setText("")
        self.pswdDblineEdit.setObjectName("pswdDblineEdit")
        self.insertDbLayout.addWidget(self.pswdDblineEdit)
        spacerItem18 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.insertDbLayout.addItem(spacerItem18)
        self.NameDblineEdit = QtWidgets.QLineEdit(self.frame)
        self.NameDblineEdit.setText("")
        self.NameDblineEdit.setObjectName("NameDblineEdit")
        self.insertDbLayout.addWidget(self.NameDblineEdit)
        spacerItem19 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.insertDbLayout.addItem(spacerItem19)
        self.portDblineEdit = QtWidgets.QLineEdit(self.frame)
        self.portDblineEdit.setText("")
        self.portDblineEdit.setObjectName("portDblineEdit")
        self.insertDbLayout.addWidget(self.portDblineEdit)
        spacerItem20 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.insertDbLayout.addItem(spacerItem20)
        self.tableDblineEdit = QtWidgets.QLineEdit(self.frame)
        self.tableDblineEdit.setText("")
        self.tableDblineEdit.setObjectName("tableDblineEdit")
        self.insertDbLayout.addWidget(self.tableDblineEdit)
        self.databaseLayout.addLayout(self.insertDbLayout)
        self.functionDbLayout = QtWidgets.QGridLayout()
        self.functionDbLayout.setObjectName("functionDbLayout")
        self.insertButton = QtWidgets.QPushButton(self.frame)
        self.insertButton.setObjectName("insertButton")
        self.functionDbLayout.addWidget(self.insertButton, 2, 1, 1, 1)
        self.configButton = QtWidgets.QPushButton(self.frame)
        self.configButton.setObjectName("configButton")
        self.functionDbLayout.addWidget(self.configButton, 0, 1, 1, 1)
        self.denoiseButton = QtWidgets.QPushButton(self.frame)
        self.denoiseButton.setObjectName("denoiseButton")
        self.functionDbLayout.addWidget(self.denoiseButton, 3, 1, 1, 1)
        self.creatButton = QtWidgets.QPushButton(self.frame)
        self.creatButton.setObjectName("creatButton")
        self.functionDbLayout.addWidget(self.creatButton, 1, 1, 1, 1)
        self.databaseLayout.addLayout(self.functionDbLayout)
        self.gridLayout_2.addLayout(self.databaseLayout, 5, 2, 1, 2)
        self.editLayout = QtWidgets.QVBoxLayout()
        self.editLayout.setObjectName("editLayout")
        self.line_2 = QtWidgets.QFrame(self.frame)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.editLayout.addWidget(self.line_2)
        self.editorlabel = QtWidgets.QLabel(self.frame)
        self.editorlabel.setObjectName("editorlabel")
        self.editLayout.addWidget(self.editorlabel)
        self.configEdLayout_2 = QtWidgets.QHBoxLayout()
        self.configEdLayout_2.setObjectName("configEdLayout_2")
        self.configEdTypeLayout = QtWidgets.QVBoxLayout()
        self.configEdTypeLayout.setObjectName("configEdTypeLayout")
        self.channelseditlabel = QtWidgets.QLabel(self.frame)
        self.channelseditlabel.setObjectName("channelseditlabel")
        self.configEdTypeLayout.addWidget(self.channelseditlabel)
        self.rateEditlabel = QtWidgets.QLabel(self.frame)
        self.rateEditlabel.setObjectName("rateEditlabel")
        self.configEdTypeLayout.addWidget(self.rateEditlabel)
        self.widthEditlabel = QtWidgets.QLabel(self.frame)
        self.widthEditlabel.setObjectName("widthEditlabel")
        self.configEdTypeLayout.addWidget(self.widthEditlabel)
        self.configEdLayout_2.addLayout(self.configEdTypeLayout)
        self.configEdLayout = QtWidgets.QVBoxLayout()
        self.configEdLayout.setObjectName("configEdLayout")
        self.channelsEditlineEdit = QtWidgets.QLineEdit(self.frame)
        self.channelsEditlineEdit.setText("")
        self.channelsEditlineEdit.setObjectName("channelsEditlineEdit")
        self.configEdLayout.addWidget(self.channelsEditlineEdit)
        self.rateEditlineEdit = QtWidgets.QLineEdit(self.frame)
        self.rateEditlineEdit.setText("")
        self.rateEditlineEdit.setObjectName("rateEditlineEdit")
        self.configEdLayout.addWidget(self.rateEditlineEdit)
        self.widthEditlineEdit = QtWidgets.QLineEdit(self.frame)
        self.widthEditlineEdit.setText("")
        self.widthEditlineEdit.setObjectName("widthEditlineEdit")
        self.configEdLayout.addWidget(self.widthEditlineEdit)
        self.configEdLayout_2.addLayout(self.configEdLayout)
        self.editLayout.addLayout(self.configEdLayout_2)
        self.functionEdLayout = QtWidgets.QHBoxLayout()
        self.functionEdLayout.setObjectName("functionEdLayout")
        spacerItem21 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.functionEdLayout.addItem(spacerItem21)
        self.editButton = QtWidgets.QPushButton(self.frame)
        self.editButton.setObjectName("editButton")
        self.functionEdLayout.addWidget(self.editButton)
        spacerItem22 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.functionEdLayout.addItem(spacerItem22)
        self.editLayout.addLayout(self.functionEdLayout)
        self.gridLayout_2.addLayout(self.editLayout, 1, 3, 1, 1)
        self.playLayout = QtWidgets.QGridLayout()
        self.playLayout.setObjectName("playLayout")
        self.line_14 = QtWidgets.QFrame(self.frame)
        self.line_14.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_14.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_14.setObjectName("line_14")
        self.playLayout.addWidget(self.line_14, 9, 0, 1, 1)
        self.line_16 = QtWidgets.QFrame(self.frame)
        self.line_16.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_16.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_16.setObjectName("line_16")
        self.playLayout.addWidget(self.line_16, 3, 1, 1, 1)
        self.line_4 = QtWidgets.QFrame(self.frame)
        self.line_4.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.playLayout.addWidget(self.line_4, 4, 0, 1, 1)
        self.line = QtWidgets.QFrame(self.frame)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.playLayout.addWidget(self.line, 0, 0, 1, 1)
        self.playFunctionLayout = QtWidgets.QHBoxLayout()
        self.playFunctionLayout.setObjectName("playFunctionLayout")
        spacerItem23 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.playFunctionLayout.addItem(spacerItem23)
        self.playButton = QtWidgets.QPushButton(self.frame)
        self.playButton.setObjectName("playButton")
        self.playFunctionLayout.addWidget(self.playButton)
        spacerItem24 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.playFunctionLayout.addItem(spacerItem24)
        self.playLayout.addLayout(self.playFunctionLayout, 5, 0, 1, 1)
        self.line_19 = QtWidgets.QFrame(self.frame)
        self.line_19.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_19.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_19.setObjectName("line_19")
        self.playLayout.addWidget(self.line_19, 5, 1, 1, 1)
        self.list = QtWidgets.QTextBrowser(self.frame)
        self.list.setObjectName("list")
        self.playLayout.addWidget(self.list, 12, 0, 1, 1)
        self.line_21 = QtWidgets.QFrame(self.frame)
        self.line_21.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_21.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_21.setObjectName("line_21")
        self.playLayout.addWidget(self.line_21, 7, 0, 1, 1)
        self.fileLayout = QtWidgets.QHBoxLayout()
        self.fileLayout.setObjectName("fileLayout")
        self.textfileLayout = QtWidgets.QVBoxLayout()
        self.textfileLayout.setObjectName("textfileLayout")
        self.inputlineEdit = QtWidgets.QLineEdit(self.frame)
        self.inputlineEdit.setText("")
        self.inputlineEdit.setObjectName("inputlineEdit")
        self.textfileLayout.addWidget(self.inputlineEdit)
        self.outputlineEdit = QtWidgets.QLineEdit(self.frame)
        self.outputlineEdit.setText("")
        self.outputlineEdit.setObjectName("outputlineEdit")
        self.textfileLayout.addWidget(self.outputlineEdit)
        self.inputFilelineEdit = QtWidgets.QLineEdit(self.frame)
        self.inputFilelineEdit.setText("")
        self.inputFilelineEdit.setObjectName("inputFilelineEdit")
        self.textfileLayout.addWidget(self.inputFilelineEdit)
        self.outputFilelineEdit = QtWidgets.QLineEdit(self.frame)
        self.outputFilelineEdit.setText("")
        self.outputFilelineEdit.setObjectName("outputFilelineEdit")
        self.textfileLayout.addWidget(self.outputFilelineEdit)
        self.fileLayout.addLayout(self.textfileLayout)
        self.openfileLayout = QtWidgets.QVBoxLayout()
        self.openfileLayout.setObjectName("openfileLayout")
        self.inputButton = QtWidgets.QPushButton(self.frame)
        self.inputButton.setObjectName("inputButton")
        self.openfileLayout.addWidget(self.inputButton)
        self.outputButton = QtWidgets.QPushButton(self.frame)
        self.outputButton.setObjectName("outputButton")
        self.openfileLayout.addWidget(self.outputButton)
        self.inputFileButton = QtWidgets.QPushButton(self.frame)
        self.inputFileButton.setObjectName("inputFileButton")
        self.openfileLayout.addWidget(self.inputFileButton)
        self.outputFileButton = QtWidgets.QPushButton(self.frame)
        self.outputFileButton.setObjectName("outputFileButton")
        self.openfileLayout.addWidget(self.outputFileButton)
        self.fileLayout.addLayout(self.openfileLayout)
        self.playLayout.addLayout(self.fileLayout, 10, 0, 1, 1)
        self.changerLayout = QtWidgets.QGridLayout()
        self.changerLayout.setObjectName("changerLayout")
        self.maleLayout = QtWidgets.QVBoxLayout()
        self.maleLayout.setObjectName("maleLayout")
        self.maleverticalSlider = QtWidgets.QSlider(self.frame)
        self.maleverticalSlider.setMaximum(1025)
        self.maleverticalSlider.setOrientation(QtCore.Qt.Vertical)
        self.maleverticalSlider.setObjectName("maleverticalSlider")
        self.maleLayout.addWidget(self.maleverticalSlider)
        self.malelabel = QtWidgets.QLabel(self.frame)
        self.malelabel.setObjectName("malelabel")
        self.maleLayout.addWidget(self.malelabel)
        self.changerLayout.addLayout(self.maleLayout, 0, 6, 1, 1)
        self.pitchLayout = QtWidgets.QVBoxLayout()
        self.pitchLayout.setObjectName("pitchLayout")
        self.pitchverticalSlider = QtWidgets.QSlider(self.frame)
        self.pitchverticalSlider.setMinimum(-20)
        self.pitchverticalSlider.setMaximum(20)
        self.pitchverticalSlider.setSingleStep(1)
        self.pitchverticalSlider.setPageStep(5)
        self.pitchverticalSlider.setOrientation(QtCore.Qt.Vertical)
        self.pitchverticalSlider.setObjectName("pitchverticalSlider")
        self.pitchLayout.addWidget(self.pitchverticalSlider)
        self.pitchlabel = QtWidgets.QLabel(self.frame)
        self.pitchlabel.setObjectName("pitchlabel")
        self.pitchLayout.addWidget(self.pitchlabel)
        self.changerLayout.addLayout(self.pitchLayout, 0, 0, 1, 1)
        self.speedLayout = QtWidgets.QVBoxLayout()
        self.speedLayout.setObjectName("speedLayout")
        self.speedverticalSlider = QtWidgets.QSlider(self.frame)
        self.speedverticalSlider.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.speedverticalSlider.setMaximum(5)
        self.speedverticalSlider.setPageStep(1)
        self.speedverticalSlider.setOrientation(QtCore.Qt.Vertical)
        self.speedverticalSlider.setInvertedAppearance(False)
        self.speedverticalSlider.setInvertedControls(False)
        self.speedverticalSlider.setObjectName("speedverticalSlider")
        self.speedLayout.addWidget(self.speedverticalSlider)
        self.speedlabel = QtWidgets.QLabel(self.frame)
        self.speedlabel.setObjectName("speedlabel")
        self.speedLayout.addWidget(self.speedlabel)
        self.changerLayout.addLayout(self.speedLayout, 0, 1, 1, 1)
        self.sampleLayout = QtWidgets.QVBoxLayout()
        self.sampleLayout.setObjectName("sampleLayout")
        self.sampleverticalSlider = QtWidgets.QSlider(self.frame)
        self.sampleverticalSlider.setMaximum(5)
        self.sampleverticalSlider.setPageStep(1)
        self.sampleverticalSlider.setProperty("value", 1)
        self.sampleverticalSlider.setOrientation(QtCore.Qt.Vertical)
        self.sampleverticalSlider.setObjectName("sampleverticalSlider")
        self.sampleLayout.addWidget(self.sampleverticalSlider)
        self.samplelabel = QtWidgets.QLabel(self.frame)
        self.samplelabel.setObjectName("samplelabel")
        self.sampleLayout.addWidget(self.samplelabel)
        self.changerLayout.addLayout(self.sampleLayout, 0, 2, 1, 1)
        self.attentionLayout = QtWidgets.QVBoxLayout()
        self.attentionLayout.setObjectName("attentionLayout")
        self.attentionverticalSlider = QtWidgets.QSlider(self.frame)
        self.attentionverticalSlider.setMinimum(-100)
        self.attentionverticalSlider.setMaximum(100)
        self.attentionverticalSlider.setOrientation(QtCore.Qt.Vertical)
        self.attentionverticalSlider.setObjectName("attentionverticalSlider")
        self.attentionLayout.addWidget(self.attentionverticalSlider)
        self.attentionlabel = QtWidgets.QLabel(self.frame)
        self.attentionlabel.setObjectName("attentionlabel")
        self.attentionLayout.addWidget(self.attentionlabel)
        self.changerLayout.addLayout(self.attentionLayout, 0, 5, 1, 1)
        self.stretchLayout = QtWidgets.QVBoxLayout()
        self.stretchLayout.setObjectName("stretchLayout")
        self.stretchverticalSlider = QtWidgets.QSlider(self.frame)
        self.stretchverticalSlider.setMinimum(1)
        self.stretchverticalSlider.setMaximum(10)
        self.stretchverticalSlider.setPageStep(2)
        self.stretchverticalSlider.setOrientation(QtCore.Qt.Vertical)
        self.stretchverticalSlider.setObjectName("stretchverticalSlider")
        self.stretchLayout.addWidget(self.stretchverticalSlider)
        self.stretchlabel = QtWidgets.QLabel(self.frame)
        self.stretchlabel.setObjectName("stretchlabel")
        self.stretchLayout.addWidget(self.stretchlabel)
        self.changerLayout.addLayout(self.stretchLayout, 0, 7, 1, 1)
        self.rebackLayout = QtWidgets.QVBoxLayout()
        self.rebackLayout.setObjectName("rebackLayout")
        self.rebackverticalSlider = QtWidgets.QSlider(self.frame)
        self.rebackverticalSlider.setMaximum(10)
        self.rebackverticalSlider.setPageStep(2)
        self.rebackverticalSlider.setProperty("value", 1)
        self.rebackverticalSlider.setOrientation(QtCore.Qt.Vertical)
        self.rebackverticalSlider.setObjectName("rebackverticalSlider")
        self.rebackLayout.addWidget(self.rebackverticalSlider)
        self.rebacklabel = QtWidgets.QLabel(self.frame)
        self.rebacklabel.setObjectName("rebacklabel")
        self.rebackLayout.addWidget(self.rebacklabel)
        self.changerLayout.addLayout(self.rebackLayout, 0, 3, 1, 1)
        self.pspeedLayout = QtWidgets.QVBoxLayout()
        self.pspeedLayout.setObjectName("pspeedLayout")
        self.pitchspeedverticalSlider = QtWidgets.QSlider(self.frame)
        self.pitchspeedverticalSlider.setMaximum(10)
        self.pitchspeedverticalSlider.setPageStep(2)
        self.pitchspeedverticalSlider.setProperty("value", 1)
        self.pitchspeedverticalSlider.setOrientation(QtCore.Qt.Vertical)
        self.pitchspeedverticalSlider.setObjectName("pitchspeedverticalSlider")
        self.pspeedLayout.addWidget(self.pitchspeedverticalSlider)
        self.pspeedlabel = QtWidgets.QLabel(self.frame)
        self.pspeedlabel.setObjectName("pspeedlabel")
        self.pspeedLayout.addWidget(self.pspeedlabel)
        self.changerLayout.addLayout(self.pspeedLayout, 0, 4, 1, 1)
        self.vagueLayout = QtWidgets.QVBoxLayout()
        self.vagueLayout.setObjectName("vagueLayout")
        self.vagueverticalSlider = QtWidgets.QSlider(self.frame)
        self.vagueverticalSlider.setMinimum(1)
        self.vagueverticalSlider.setMaximum(10)
        self.vagueverticalSlider.setPageStep(2)
        self.vagueverticalSlider.setOrientation(QtCore.Qt.Vertical)
        self.vagueverticalSlider.setObjectName("vagueverticalSlider")
        self.vagueLayout.addWidget(self.vagueverticalSlider)
        self.vaguelabel = QtWidgets.QLabel(self.frame)
        self.vaguelabel.setObjectName("vaguelabel")
        self.vagueLayout.addWidget(self.vaguelabel)
        self.changerLayout.addLayout(self.vagueLayout, 0, 8, 1, 1)
        self.playLayout.addLayout(self.changerLayout, 8, 0, 1, 1)
        self.oscillogram = QtWidgets.QLabel(self.frame)
        self.oscillogram.setMinimumSize(QtCore.QSize(300, 100))
        self.oscillogram.setObjectName("oscillogram")
        self.playLayout.addWidget(self.oscillogram, 1, 0, 1, 1)
        self.functionFileLayout = QtWidgets.QHBoxLayout()
        self.functionFileLayout.setObjectName("functionFileLayout")
        spacerItem25 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.functionFileLayout.addItem(spacerItem25)
        self.openButton = QtWidgets.QPushButton(self.frame)
        self.openButton.setObjectName("openButton")
        self.functionFileLayout.addWidget(self.openButton)
        spacerItem26 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.functionFileLayout.addItem(spacerItem26)
        self.saveButton = QtWidgets.QPushButton(self.frame)
        self.saveButton.setObjectName("saveButton")
        self.functionFileLayout.addWidget(self.saveButton)
        spacerItem27 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.functionFileLayout.addItem(spacerItem27)
        self.playLayout.addLayout(self.functionFileLayout, 11, 0, 1, 1)
        self.gridLayout_2.addLayout(self.playLayout, 1, 0, 5, 1)
        self.line_6 = QtWidgets.QFrame(self.frame)
        self.line_6.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_6.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_6.setObjectName("line_6")
        self.gridLayout_2.addWidget(self.line_6, 4, 2, 1, 2)
        self.locationLayout = QtWidgets.QVBoxLayout()
        self.locationLayout.setObjectName("locationLayout")
        self.locationlabel = QtWidgets.QLabel(self.frame)
        self.locationlabel.setObjectName("locationlabel")
        self.locationLayout.addWidget(self.locationlabel)
        self.cartesianGrid = QtWidgets.QLabel(self.frame)
        self.cartesianGrid.setMinimumSize(QtCore.QSize(300, 200))
        self.cartesianGrid.setObjectName("cartesianGrid")
        self.locationLayout.addWidget(self.cartesianGrid)
        self.functionLocationlLayout = QtWidgets.QHBoxLayout()
        self.functionLocationlLayout.setObjectName("functionLocationlLayout")
        spacerItem28 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.functionLocationlLayout.addItem(spacerItem28)
        self.locationButton = QtWidgets.QPushButton(self.frame)
        self.locationButton.setObjectName("locationButton")
        self.functionLocationlLayout.addWidget(self.locationButton)
        spacerItem29 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.functionLocationlLayout.addItem(spacerItem29)
        self.locationLayout.addLayout(self.functionLocationlLayout)
        self.gridLayout_2.addLayout(self.locationLayout, 5, 5, 1, 2)
        self.silenceLayout = QtWidgets.QVBoxLayout()
        self.silenceLayout.setObjectName("silenceLayout")
        self.line_3 = QtWidgets.QFrame(self.frame)
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.silenceLayout.addWidget(self.line_3)
        self.Mutelabel = QtWidgets.QLabel(self.frame)
        self.Mutelabel.setObjectName("Mutelabel")
        self.silenceLayout.addWidget(self.Mutelabel)
        self.configMutelLayout = QtWidgets.QHBoxLayout()
        self.configMutelLayout.setObjectName("configMutelLayout")
        self.configMutetypeLayout = QtWidgets.QVBoxLayout()
        self.configMutetypeLayout.setObjectName("configMutetypeLayout")
        self.keepMutelabel = QtWidgets.QLabel(self.frame)
        self.keepMutelabel.setObjectName("keepMutelabel")
        self.configMutetypeLayout.addWidget(self.keepMutelabel)
        self.minMutelabel = QtWidgets.QLabel(self.frame)
        self.minMutelabel.setObjectName("minMutelabel")
        self.configMutetypeLayout.addWidget(self.minMutelabel)
        self.threshMutelabel = QtWidgets.QLabel(self.frame)
        self.threshMutelabel.setObjectName("threshMutelabel")
        self.configMutetypeLayout.addWidget(self.threshMutelabel)
        self.configMutelLayout.addLayout(self.configMutetypeLayout)
        self.insertMuteLayout = QtWidgets.QVBoxLayout()
        self.insertMuteLayout.setObjectName("insertMuteLayout")
        self.keepMutelineEdit = QtWidgets.QLineEdit(self.frame)
        self.keepMutelineEdit.setText("")
        self.keepMutelineEdit.setObjectName("keepMutelineEdit")
        self.insertMuteLayout.addWidget(self.keepMutelineEdit)
        self.minMutelineEdit = QtWidgets.QLineEdit(self.frame)
        self.minMutelineEdit.setText("")
        self.minMutelineEdit.setObjectName("minMutelineEdit")
        self.insertMuteLayout.addWidget(self.minMutelineEdit)
        self.threshMutelineEdit = QtWidgets.QLineEdit(self.frame)
        self.threshMutelineEdit.setText("")
        self.threshMutelineEdit.setObjectName("threshMutelineEdit")
        self.insertMuteLayout.addWidget(self.threshMutelineEdit)
        self.configMutelLayout.addLayout(self.insertMuteLayout)
        self.silenceLayout.addLayout(self.configMutelLayout)
        self.functionMuteLayout = QtWidgets.QHBoxLayout()
        self.functionMuteLayout.setObjectName("functionMuteLayout")
        spacerItem30 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.functionMuteLayout.addItem(spacerItem30)
        self.stripButton = QtWidgets.QPushButton(self.frame)
        self.stripButton.setObjectName("stripButton")
        self.functionMuteLayout.addWidget(self.stripButton)
        spacerItem31 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.functionMuteLayout.addItem(spacerItem31)
        self.removeButton = QtWidgets.QPushButton(self.frame)
        self.removeButton.setObjectName("removeButton")
        self.functionMuteLayout.addWidget(self.removeButton)
        spacerItem32 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.functionMuteLayout.addItem(spacerItem32)
        self.splitButton = QtWidgets.QPushButton(self.frame)
        self.splitButton.setObjectName("splitButton")
        self.functionMuteLayout.addWidget(self.splitButton)
        spacerItem33 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.functionMuteLayout.addItem(spacerItem33)
        self.silenceLayout.addLayout(self.functionMuteLayout)
        self.gridLayout_2.addLayout(self.silenceLayout, 1, 6, 1, 1)
        self.line_5 = QtWidgets.QFrame(self.frame)
        self.line_5.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_5.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_5.setObjectName("line_5")
        self.gridLayout_2.addWidget(self.line_5, 2, 3, 1, 1)
        self.line_7 = QtWidgets.QFrame(self.frame)
        self.line_7.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_7.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_7.setObjectName("line_7")
        self.gridLayout_2.addWidget(self.line_7, 2, 6, 1, 1)
        self.gridLayout.addWidget(self.frame, 0, 0, 1, 1)

        self.retranslateUi(AudioProcess)
        QtCore.QMetaObject.connectSlotsByName(AudioProcess)

    def retranslateUi(self, AudioProcess):
        _translate = QtCore.QCoreApplication.translate
        AudioProcess.setWindowTitle(_translate("AudioProcess", "Form"))
        self.titlelabel.setText(_translate("AudioProcess", "<html><head/><body><p><span style=\" font-size:14pt; font-weight:600; font-style:italic; color:#aaaaff;\">Audio Process</span></p></body></html>"))
        self.helpButton.setText(_translate("AudioProcess", "help"))
        self.normalizerlabel.setText(_translate("AudioProcess", "<html><head/><body><p align=\"center\"><span style=\" color:#aaaaff;\">Normalizer</span></p></body></html>"))
        self.maxSilenceNomalizerlabel.setText(_translate("AudioProcess", "<html><head/><body><p align=\"center\"><span style=\" color:#aaaaff;\">max silence</span></p></body></html>"))
        self.targerNomalizerlabel.setText(_translate("AudioProcess", "<html><head/><body><p align=\"center\"><span style=\" color:#aaaaff;\">target dBFS</span></p></body></html>"))
        self.nomalizercomboBox.setItemText(0, _translate("AudioProcess", "both"))
        self.nomalizercomboBox.setItemText(1, _translate("AudioProcess", "increase only"))
        self.nomalizercomboBox.setItemText(2, _translate("AudioProcess", "decrease only"))
        self.muteButton.setText(_translate("AudioProcess", "mute"))
        self.volumeButton.setText(_translate("AudioProcess", "volume"))
        self.recoedlabel.setText(_translate("AudioProcess", "<html><head/><body><p align=\"center\"><span style=\" color:#aaaaff;\">Recording</span></p></body></html>"))
        self.micidRecordlabel.setText(_translate("AudioProcess", "<html><head/><body><p align=\"center\"><span style=\" color:#aaaaff;\">MicID</span></p></body></html>"))
        self.chunkRecordlabel.setText(_translate("AudioProcess", "<html><head/><body><p align=\"center\"><span style=\" color:#aaaaff;\">chunk</span></p></body></html>"))
        self.channelsRecordlabel.setText(_translate("AudioProcess", "<html><head/><body><p align=\"center\"><span style=\" color:#aaaaff;\">channels</span></p></body></html>"))
        self.rateRecordlabel.setText(_translate("AudioProcess", "<html><head/><body><p align=\"center\"><span style=\" color:#aaaaff;\">rate</span></p></body></html>"))
        self.timelabel.setText(_translate("AudioProcess", "<html><head/><body><p align=\"center\"><span style=\" color:#aaaaff;\">time</span></p></body></html>"))
        self.micButton.setText(_translate("AudioProcess", "Mic"))
        self.recordButton.setText(_translate("AudioProcess", "record"))
        self.configDblabel.setText(_translate("AudioProcess", "<html><head/><body><p align=\"center\"><span style=\" color:#aaaaff;\">config type</span></p></body></html>"))
        self.hostlDbabel.setText(_translate("AudioProcess", "<html><head/><body><p align=\"center\"><span style=\" color:#aaaaff;\">host</span></p></body></html>"))
        self.userDblabel.setText(_translate("AudioProcess", "<html><head/><body><p align=\"center\"><span style=\" color:#aaaaff;\">user</span></p></body></html>"))
        self.passwdlabel.setText(_translate("AudioProcess", "<html><head/><body><p align=\"center\"><span style=\" color:#aaaaff;\">passwd</span></p></body></html>"))
        self.databaseDblabel.setText(_translate("AudioProcess", "<html><head/><body><p align=\"center\"><span style=\" color:#aaaaff;\">database</span></p></body></html>"))
        self.portlDbabel.setText(_translate("AudioProcess", "<html><head/><body><p align=\"center\"><span style=\" color:#aaaaff;\">port</span></p></body></html>"))
        self.tablelabel.setText(_translate("AudioProcess", "<html><head/><body><p align=\"center\"><span style=\" color:#aaaaff;\">table</span></p></body></html>"))
        self.insertDblabel.setText(_translate("AudioProcess", "<html><head/><body><p><span style=\" font-size:10pt; color:#aaaaff;\">Input music_wav database</span></p></body></html>"))
        self.insertButton.setText(_translate("AudioProcess", "Insert file"))
        self.configButton.setText(_translate("AudioProcess", "Config db"))
        self.denoiseButton.setText(_translate("AudioProcess", "Denoise"))
        self.creatButton.setText(_translate("AudioProcess", "Creat table"))
        self.editorlabel.setText(_translate("AudioProcess", "<html><head/><body><p align=\"center\"><span style=\" color:#aaaaff;\">Editor</span></p></body></html>"))
        self.channelseditlabel.setText(_translate("AudioProcess", "<html><head/><body><p align=\"center\"><span style=\" color:#aaaaff;\">channels</span></p></body></html>"))
        self.rateEditlabel.setText(_translate("AudioProcess", "<html><head/><body><p align=\"center\"><span style=\" color:#aaaaff;\">rate</span></p></body></html>"))
        self.widthEditlabel.setText(_translate("AudioProcess", "<html><head/><body><p align=\"center\"><span style=\" color:#aaaaff;\">width</span></p></body></html>"))
        self.editButton.setText(_translate("AudioProcess", "edit"))
        self.playButton.setText(_translate("AudioProcess", "play"))
        self.inputButton.setText(_translate("AudioProcess", "input"))
        self.outputButton.setText(_translate("AudioProcess", "output"))
        self.inputFileButton.setText(_translate("AudioProcess", "input file"))
        self.outputFileButton.setText(_translate("AudioProcess", "output file"))
        self.malelabel.setText(_translate("AudioProcess", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600; color:#aaaaff;\"> male </span></p></body></html>"))
        self.pitchlabel.setText(_translate("AudioProcess", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600; color:#aaaaff;\">pitch</span></p></body></html>"))
        self.speedlabel.setText(_translate("AudioProcess", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600; color:#aaaaff;\">speed</span></p></body></html>"))
        self.samplelabel.setText(_translate("AudioProcess", "<html><head/><body><p align=\"center\"><span style=\" color:#aaaaff;\">sample</span></p></body></html>"))
        self.attentionlabel.setText(_translate("AudioProcess", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600; color:#aaaaff;\">attent</span></p></body></html>"))
        self.stretchlabel.setText(_translate("AudioProcess", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600; color:#aaaaff;\">stretc</span></p></body></html>"))
        self.rebacklabel.setText(_translate("AudioProcess", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600; color:#aaaaff;\">reback</span></p></body></html>"))
        self.pspeedlabel.setText(_translate("AudioProcess", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600; color:#aaaaff;\">pspeed</span></p></body></html>"))
        self.vaguelabel.setText(_translate("AudioProcess", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600; color:#aaaaff;\">vague</span></p></body></html>"))
        self.oscillogram.setText(_translate("AudioProcess", "<html><head/><body><p align=\"center\"><span style=\" color:#aaaaff;\">oscillogram</span></p></body></html>"))
        self.openButton.setText(_translate("AudioProcess", "open"))
        self.saveButton.setText(_translate("AudioProcess", "save"))
        self.locationlabel.setText(_translate("AudioProcess", "<html><head/><body><p align=\"center\"><span style=\" color:#aaaaff;\">Sound Localization</span></p></body></html>"))
        self.cartesianGrid.setText(_translate("AudioProcess", "<html><head/><body><p align=\"center\"><span style=\" color:#aaaaff;\">cartesianGrid</span></p></body></html>"))
        self.locationButton.setText(_translate("AudioProcess", "location"))
        self.Mutelabel.setText(_translate("AudioProcess", "<html><head/><body><p align=\"center\"><span style=\" color:#aaaaff;\">Mute</span></p></body></html>"))
        self.keepMutelabel.setText(_translate("AudioProcess", "<html><head/><body><p align=\"center\"><span style=\" color:#aaaaff;\">keep</span></p></body></html>"))
        self.minMutelabel.setText(_translate("AudioProcess", "<html><head/><body><p align=\"center\"><span style=\" color:#aaaaff;\">min</span></p></body></html>"))
        self.threshMutelabel.setText(_translate("AudioProcess", "<html><head/><body><p align=\"center\"><span style=\" color:#aaaaff;\">thresh</span></p></body></html>"))
        self.stripButton.setText(_translate("AudioProcess", "strip"))
        self.removeButton.setText(_translate("AudioProcess", "remove"))
        self.splitButton.setText(_translate("AudioProcess", "split"))
